### ISSUE TITLE
plugins does not work with latest cockpit

### ISSUE THREAD

**Issue by ohadlevy** [theforeman/foreman_cockpit#4]
when opening cockpit tab, I'm getting:

```
Things have moved

This old version of Cockpit doesn't know where to find default pages. Use the navigation menus to help it find its way.
```

**Comment by dLobatog** [comment]
Should be fixed with https://github.com/theforeman/foreman_cockpit/commit/f414ff2e7333c65cf8786257ae0575036cba3c0d which I'll release shortly. I also got in contact with the Cockpit team which might make future changes in URLs redirect to the new ones, or offer a 'version' field on the 9090/ping endpoint
